Fix links to git-annex's managed files
Datalad's `ls' command fails with an error on links to git-annex files
maybe because of the 2 levels redirections:

Traceback (most recent call last):
  File "venv/lib/python3.7/site-packages/datalad/interface/ls.py" line 149, in __call__
    return _ls_json(loc json=json, **kw) if json else _ls_dataset(loc, **kw)
  File "venv/lib/python3.7/site-packages/datalad/interface/ls_webui.py" line 442, in _ls_json
    **kwargs)
  File "venv/lib/python3.7/site-packages/datalad/interface/ls_webui.py" line 357, in ds_traverse
    json=json
  File "venv/lib/python3.7/site-packages/datalad/interface/ls_webui.py" line 279, in fs_traverse
    basepath=basepath or path)
  File "venv/lib/python3.7/site-packages/datalad/interface/ls_webui.py" line 279, in fs_traverse
    basepath=basepath or path)
  File "venv/lib/python3.7/site-packages/datalad/interface/ls_webui.py" line 220, in fs_traverse
    fs = fs_extract(path repo, basepath=basepath or path)
  File "venv/lib/python3.7/site-packages/datalad/interface/ls_webui.py" line 125, in fs_extract
    for stype svalue in node.size.items()
  File "venv/lib/python3.7/site-packages/datalad/interface/ls.py" line 331, in size
    size = self.repo.info(self._path batch=True)['size']
TypeError: 'NoneType' object is not subscriptable